import { RiskLevel } from '../api/client'

interface RiskScoreWidgetProps {
  riskScore?: number
  riskLevel?: RiskLevel
  isSimulated?: boolean
}

const RISK_COLORS: Record<RiskLevel, string> = {
  Critical: '#ef4444',
  High: '#f97316',
  Medium: '#eab308',
  Low: '#22c55e',
}

function WidgetShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex flex-1 flex-col border border-border bg-background p-7">
      {children}
    </div>
  )
}

function WidgetTitle({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="text-xs font-medium uppercase tracking-widest text-foreground-muted">
      {children}
    </h3>
  )
}

function RiskScoreWidget({ riskScore, riskLevel, isSimulated }: RiskScoreWidgetProps) {
  const score = riskScore ?? 91
  const level: RiskLevel = riskLevel ?? 'Critical'
  const color = RISK_COLORS[level]

  return (
    <WidgetShell>
      <div className="flex flex-row items-center justify-between">
        <WidgetTitle>Risk Score</WidgetTitle>
        {isSimulated && (
          <span
            title="No trained model artifacts matched this account, or no live model is loaded. This result is generated by a deterministic simulator, not the real ensemble - do not treat it as a verified prediction."
            className="inline-flex items-center bg-[#ef4444] px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-white"
          >
            Simulated
          </span>
        )}
      </div>
      <div className="mt-4 flex flex-row items-baseline justify-center gap-2">
        <span className="text-7xl font-bold leading-none text-foreground">
          {score}
        </span>
        <span className="text-lg text-foreground-muted">/1000</span>
      </div>
      <div className="mt-6 h-[2px] w-full bg-foreground" />
      <div className="mt-4 flex flex-row items-center justify-between">
        <p className="text-xs text-foreground-muted">Risk Level</p>
        <span
          className="inline-flex items-center px-2 py-1 text-[11px] font-bold uppercase tracking-wider text-foreground"
          style={{ backgroundColor: color, color: '#000000' }}
        >
          {level}
        </span>
      </div>
    </WidgetShell>
  )
}

export default RiskScoreWidget
export { RISK_COLORS, WidgetShell, WidgetTitle }