import { RiskLevel } from '../api/client'

interface RiskScoreWidgetProps {
  riskScore?: number
  riskLevel?: RiskLevel
  isSimulated?: boolean
}

const RISK_COLORS: Record<RiskLevel, string> = {
  Critical: '#ef4444',
  High: '#f97316',
  Medium: '#eab308',
  Low: '#22c55e',
}

// Tier-matched glow shadows for the Risk Level badge — same hues as
// the palette, kept subtle so the badge stays legible.
const RISK_GLOWS: Record<RiskLevel, string> = {
  Critical: '0 0 12px rgba(239, 68, 68, 0.4)',
  High: '0 0 12px rgba(249, 115, 22, 0.4)',
  Medium: '0 0 12px rgba(234, 179, 8, 0.4)',
  Low: '0 0 12px rgba(34, 197, 94, 0.4)',
}

// Default glass widget shell — used by every widget. The base look is
// glassmorphism; individual widgets layer glow-cyan / glow-purple on
// top via the `extraClassName` slot.
function WidgetShell({
  children,
  extraClassName = '',
}: {
  children: React.ReactNode
  extraClassName?: string
}) {
  return (
    <div className={`glass flex flex-1 flex-col p-7 ${extraClassName}`}>
      {children}
    </div>
  )
}

function WidgetTitle({ children }: { children: React.ReactNode }) {
  return (
    <h3
      className="text-xs font-medium uppercase"
      style={{
        letterSpacing: '0.18em',
        color: '#cbd5e1',
      }}
    >
      {children}
    </h3>
  )
}

function RiskScoreWidget({ riskScore, riskLevel, isSimulated }: RiskScoreWidgetProps) {
  const score = riskScore ?? 91
  const level: RiskLevel = riskLevel ?? 'Critical'
  const color = RISK_COLORS[level]
  const glow = RISK_GLOWS[level]

  return (
    <WidgetShell extraClassName="glow-cyan">
      <div className="flex flex-row items-center justify-between">
        <WidgetTitle>Risk Score</WidgetTitle>
        {isSimulated && (
          <span
            title="No trained model artifacts matched this account, or no live model is loaded. This result is generated by a deterministic simulator, not the real ensemble - do not treat it as a verified prediction."
            className="inline-flex items-center bg-[#ef4444] px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-white"
          >
            Simulated
          </span>
        )}
      </div>
      <div className="mt-4 flex flex-row items-baseline justify-center gap-2">
        {/* Cyan → purple gradient on the headline score. */}
        <span
          className="text-7xl font-bold leading-none text-gradient-cyan-purple"
        >
          {score}
        </span>
        <span className="text-lg text-[#cbd5e1]">/1000</span>
      </div>
      <div
        className="mt-6 h-[2px] w-full"
        style={{ backgroundColor: 'rgba(255, 255, 255, 0.06)' }}
      />
      <div className="mt-4 flex flex-row items-center justify-between">
        <p
          className="text-xs font-medium uppercase"
          style={{ color: '#cbd5e1', letterSpacing: '0.18em' }}
        >
          Risk Level
        </p>
        <span
          className="inline-flex items-center px-2 py-1 text-[11px] font-bold uppercase tracking-wider"
          style={{
            backgroundColor: color,
            color: '#000000',
            boxShadow: glow,
          }}
        >
          {level}
        </span>
      </div>
    </WidgetShell>
  )
}

export default RiskScoreWidget
export { RISK_COLORS, WidgetShell, WidgetTitle }
